theme = "flavours"

[editor]
line-number = "relative"
mouse = true
scrolloff = 99
cursorline = true
default-yank-register = "+"
auto-format = false
completion-timeout = 50
color-modes = true
popup-border = "none"
clipboard-provider = "wayland"

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.gutters.line-numbers]
min-width = 4

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["spacer"]
right = ["workspace-diagnostics", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
separator = " "
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "·"
