windowrule {
  name = dolphin-popup
  match:class = org.kde.dolphin
  match:title = (Copying.*|.*File.*Exists.*)
  float = true
  center = true
  size = 600 400
}

windowrule {
  name = dolphin-file-exists
  match:class = org.kde.dolphin
  match:title = File Already Exists - Dolphin
  float = true
  center = true
  size = 600 800
}
