windowrule {
  name = qt-floating-configuraiton-tool
  match:class = qt\d+ct
  float = true
  center = true
  size = 800 500
}

windowrule {
  name = kvantum-floating-configuraiton-tool
  match:title = Kvantum Manager
  float = true
  center = true
  size = 800 500
}
