# Float Steam
windowrule {
  name = steam
  opacity = 1 1
  match:class = steam
  idle_inhibit = fullscreen
}

windowrule {
  name = steam-friend-list
  match:class= steam
  match:title=Friends List
  float=on
  size = 460 800
}

