[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Neovim", for = "unix" },
  { run = "nvim %*", block = true, desc = "Neovim", for = "windows" },
]

play = [
  # { run = 'ffplay "$@"', block = true, desc = "FFplay", for = "macos" }
  { run = "ffplay %1", block = true, desc = "FFplay", for = "windows" },
]
