[3dview]
colorscheme=DeepOcean

[advanced]
applicationFontFamily=Roboto
applicationFontSize=11
consoleFontFamily=RobotoMono Nerd Font [GOOG]
consoleFontSize=10
customizerFontFamily=Roboto
customizerFontSize=11
toolbarExport2D=dxf
toolbarExport3D=asciistl

[design]
autoReload=true

[editor]
indentStyle=Spaces
lineWrap=None
syntaxhighlight=Tomorrow Night

[printing]
localAppFileFormat=asciistl
octoPrintFileFormat=asciistl
printServiceFileFormat=asciistl

[view]
hide3DViewToolbar=false
hideConsole=false
hideCustomizer=true
hideEditor=false
hideEditorToolbar=false
hideErrorLog=false
orthogonalProjection=true
showAxes=true
showEdges=false
showScaleProportional=true
