source = ./apps.conf

windowrule {
  name = floating-tui-window
  float = on
  center = on
  size = 1200 800
  match:class = minsh.floating.*|.*localsend.*
}

windowrule {
  name = chromium-based-browser-wr
  match:class = ((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)
  tag = +chromium-based-browser
}

windowrule {
  name = firefox-based-browser-wr
  match:class = (.*[fF]irefox.*|.*zen.*|.*librewolf.*)
  tag = +firefox-based-browser
}

windowrule {
  name = browser-opacity
  opacity = 1 0.97
  match:tag = firefox-based-browser
}

windowrule {
  name = no_transparency_for_video_sites
  opacity = 1.0 1.0
  match:title = (?i).*(\byoutube\b|\btwitch\b|\btelegram\b).*
}

windowrule {
  name  = minsh-shadow
  match:namespace = minsh
  no_anim = off
}

layerrule {
  name = disable_animations_hyprshot
  no_anim = true
  match:title = hyprshot|walker|rofi
}

windowrule {
  name = bambulab_on_5th_workspace
  match:class = BambuStudio
  workspace = 5
}
