# source = monitors.conf
source = input.conf
source = bindings.conf
source = looknfeel.conf
source = plugins.conf
source = autostart.conf
source = hyprwindowrules.conf
source = userconfig.conf
source = envs.conf
# for testing some things
source = hyprtest.conf


