$base00 = rgb(262427)
$base01 = rgb(3b393c)
$base02 = rgb(514f52)
$base03 = rgb(676567)
$base04 = rgb(7c7b7d)
$base05 = rgb(fcfcfc)
$base06 = rgb(eae9eb)
$base07 = rgb(fcfcfc)
$base08 = rgb(ff7272)
$base09 = rgb(fc9d6f)
$base0A = rgb(ffca58)
$base0B = rgb(bcdf59)
$base0C = rgb(aee8f4)
$base0D = rgb(49cae4)
$base0E = rgb(a093e2)
$base0F = rgb(ff8787)

$base10 = rgb(262427)
$base11 = rgb(262427)
$base12 = rgb(ff7272)
$base13 = rgb(ffca58)
$base14 = rgb(bcdf59)
$base15 = rgb(aee8f4)
$base16 = rgb(49cae4)
$base17 = rgb(a093e2)