# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  kb_layout = us, ru
  kb_options = grp:alt_shift_toggle
  repeat_delay = 200
  repeat_rate=72

  sensitivity = -0.75

  touchpad {
    scroll_factor = 0.4
  }
}

# Scroll nicely in the terminal
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace
