exec-once = hyprpm reload 

plugin {
  hyprbars {
    enabled = false
    bar_height = 24
    bar_color = $base01
    col.text = $base05
    bar_text_size = 8
    bar_text_font = CaskaydiaCove Nerd Font
    bar_button_padding = 8
    bar_padding = 8
    bar_part_of_window = true
    icon_on_hover = false
    bar_precedence_over_border = false
    on_double_click = hyprctl dispatch togglefloating
    hyprbars-button = $base08, 12, , hyprctl dispatch killactive
    hyprbars-button = $base0A, 12, , hyprctl dispatch fullscreen 2
    hyprbars-button = $base0B, 12, , hyprctl dispatch togglefloating
  }

  dynamic-cursors {
    enabled = true
    mode = none # rotate | tilt | stretch

    shake {
      threshold = 5.0
      limit = 6.0
      timeout = 1000
      effects = 1 # rotate | tilt | stretch: 1
    }
  }
}
