background #262427
foreground #fcfcfc
selection_background #fcfcfc
selection_foreground #262427
url_color #7c7b7d
cursor #fcfcfc
cursor_text_color #262427
active_border_color #676567
inactive_border_color #3b393c
active_tab_background #262427
active_tab_foreground #fcfcfc
inactive_tab_background #3b393c
inactive_tab_foreground #7c7b7d
tab_bar_background #3b393c
wayland_titlebar_color #262427
macos_titlebar_color #262427

# normal
color0 #262427
color1 #ff7272
color2 #bcdf59
color3 #ffca58
color4 #49cae4
color5 #a093e2
color6 #aee8f4
color7 #fcfcfc

# bright
color8 #676567
color9 #ff7272
color10 #bcdf59
color11 #ffca58
color12 #49cae4
color13 #a093e2
color14 #aee8f4
color15 #fcfcfc

# extended base16 colors
color16 #fc9d6f
color17 #ff8787
color18 #3b393c
color19 #514f52
color20 #7c7b7d
color21 #eae9eb
