shell = "zsh -c '{}'"

[[items]] # kitty
file = "~/.local/share/kitty/theme.conf"
template = "kitty"
subtemplate = "default-256"                                              # later switch to `default-256`
rewrite = true
hook = "kitty @ set-colors --all '~/.local/share/kitty/theme.conf'"

[[items]] # foot
file = "~/.config/foot/foot.ini"
template = "foot"
rewrite = false
start = "# start flavours"
end = "# end flavours"

[[items]] # neovim
file = "~/.local/share/nvim/theme.lua"
template = "neovim"
rewrite = true

[[items]] # zathura
file = "~/.local/share/zathura/theme"
template = "zathura"
rewrite = true

[[items]] # fzf
file = "~/.local/share/zsh/fzf_theme.sh"
template = "fzf"
subtemplate = "base16-default"
rewrite = true

[[items]] # quickshell minsh
file = "~/.cache/quickshell/minsh/colorscheme.json"
template = "styles"
subtemplate = "json"
rewrite = true

[[items]] # btop
file = "~/.config/btop/themes/flavours.theme"
template = "btop"
rewrite = true

[[items]] # mako
file = "~/.config/mako/theme"
template = "mako"
rewrite = true
hook = "makoctl reload"

[[items]] # hyprland
file = "~/.config/hypr/hyprcolors.conf"
template = "hyprland"
rewrite = true

[[items]] # yazi
file = "~/.config/yazi/theme.toml"
template = "yazi"
rewrite = true

[[items]] # bat
file = "~/.config/bat/themes/flavours.tmTheme"
template = "textmate"
rewrite = true
hook = "bat cache --build"

[[items]] # pywal
file = "~/.cache/wal/colors.json"
template = "pywal"
rewrite = true
hook = "pywalfox update"

# [[items]] # kvantum
# file = "~/.config/Kvantum/flavours/flavours.kvconfig"
# template = "Kvantum"
# subtemplate = "stylix_theme"
# rewrite = true
# hook = "kvantummanager --set flavours"

# [[items]] # kvantum svg
# file = "~/.config/Kvantum/flavours/flavours.svg"
# template = "Kvantum"
# subtemplate = "stylix_theme_svg"
# rewrite = true

[[items]] # tmux
file = "~/.local/share/tmux/theme.conf"
template = "tmux"
subtemplate = "base16"
rewrite = true


[[items]] # zellij
file = "~/.config/zellij/themes/flavours.kdl"
template = "zellij"
subtemplate = "default"
rewrite = true

[[items]] # cava
file = "~/.config/cava/cava.ini"
template = "cava"
rewrite = true

[[items]] # vimiv
file = "~/.config/vimiv/styles/flavours"
template = "vimiv"
rewrite = true

[[items]] # gtk
file = "~/.config/gtk/colors.css"
template = "gtk"
rewrite = true

[[items]] # gtk 3
file = "~/.config/gtk-3.0/colors.css"
template = "gtk"
rewrite = true
hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[[items]] # gtk 4
file = "~/.config/gtk-4.0/colors.css"
template = "gtk"
rewrite = true

[[items]] # wlr-which-key
file = "~/.config/wlr-which-key/config.yaml"
template = "wlr-which-key"
rewrite = false
start = "# start flavours"
end = "# end flavours"

[[items]] # helix
file = "~/.config/helix/themes/flavours.toml"
template = "helix"
rewrite = true

# godot
# gtk-flatcolor
# gtk2
# spotify
# vim
# vscode
